export const MAP =  {
    "cytosol": "Cytosols",
    "intermediate_filament": "Intermediate Filaments",
    "actin_filament": "Actin Filaments",
    "focal_adhesion_site": "Focal Adhesion Sites",
    "microtubule_organizing_center": "Microtubule Organization Centers",
    "centrosome": "Centrosomes",
    "microtubule": "Microtubules",
    "microtubule_end": "Microtubule Ends",
    "secreted_protein": "Secreted Proteins",
    "lipid_droplet": "Lipid Droplets",
    "lysosome": "Lysosomes",
    "peroxisome": "Peroxisomes",
    "endosome": "Endosomes",
    "endoplasmic_reticulum": "Endoplasmic Reticulums",
    "golgi_apparatus": "Golgi Apparatus",
    "nucleoplasm": "Nucleoplasms",
    "nuclear_membrane": "Nuclear Membrane",
    "nuclear_body": "Nuclear Bodies",
    "nuclear_speckle": "Nuclear Speckles",
    "nucleolus": "Nucleoli",
    "nucleoli_fibrillar_center": "Nucleoli Fibrillar Centers",
    "rods_and_ring": "Rods and Rings",
    "mitochondrion": "Mitochondria",
    "plasma_membrane": "Plasma Membrane",
}